config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  resources :parcels
  root "static_pages#home"
  get "/search", to: "parcels#index"
  post "/search", to: "parcels#search"
  get "auth/:provider/callback", to: "sessions#create"
  post "/login", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  get "/signout", to: "sessions#destroy", as: "signout"
  get "/login", to: "sessions#new"

  resources :sessions, only: [:create, :destroy]
  resources :users, only: [:edit, :update, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parcel.rb
class Parcel < ApplicationRecord
  validates(:name, presence: true, length: {maximum: 50})
  validates(:quantity, presence: true)
  validates(:phone, presence: true, length: {maximum: 15})
  default_scope -> {order(created_at: :desc)}
  def self.search(search_type, search_key)
    if Rails.env.production?
      Parcel.where("#{search_type} ILIKE ?", "%#{search_key}%")
    else
      Parcel.where("#{search_type} LIKE ?", "%#{search_key}%")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  def authenticated?(password)
    return false if password_digest.nil?
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def self.digest(password)
    BCrypt::Password.create(password)
  end

  def self.new_token
    SecureRandom::urlsafe_base64
  end
    
  def self.from_omniauth(auth)
    if user == User.find_by(email: auth.info.email)
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    else
      user = User.new
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    end
    user.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  include SessionsHelper
  before_action :check_logged_in

  def home
  end

  private

  def check_logged_in
    unless logged_in?
      flash[:danger] = 'Log in is required.'
      redirect_to root_url
    end
  end

  def check_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController
  before_action :set_parcel, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:new, :edit, :update, :destroy]
  #before_action :check_admin, only: [:new, :create]
  # GET /parcels
  # GET /parcels.json
  def index
    @parcels = Parcel.paginate(page: params[:page])
    
  end

  # GET /parcels/1
  # GET /parcels/1.json
  def show
  end

  # GET /parcels/new
  def new
    
    @parcel = Parcel.new
    @error_messages = []
  end
  
  def search
    @parcels = Parcel.search(params[:search][:search_type], params[:search][:search_key]).paginate(page: params[:page])
    @search_type = params[:search][:search_type]
    @search_key = params[:search][:search_key]
    
    render "index"
  end



  # GET /parcels/1/edit
  def edit
    
  end

  # POST /parcels
  # POST /parcels.json
  def create
    parcels = params["parcel"]
    @error_messages = []
    parcels.each do |f|
      parcel = parcels[f]
      new_parcel = Parcel.new(name: parcel["name"], quantity: parcel["quantity"].to_i, phone: parcel["phone"], courier: parcel["courier"], remarks: parcel["remarks"])
      unless new_parcel.save
        unless parcel["name"] == "" && quantity == "" && phone == ""
          @error_messages << "Parcel #{f.to_i+1} is not saved, possibly due to empty field"
        end
      end
    end
    if @error_messages.empty?
      flash.now[:info] = "All parcels are saved successfully!"
      
    end
    render "new"
  end
=begin
    @parcel = Parcel.new(parcel_params)
    respond_to do |format|
      if @parcel.save
        format.html { redirect_to @parcel, notice: 'Parcel was successfully created.' }
        format.json { render :show, status: :created, location: @parcel }
      else
        format.html { render :new }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
=end

  # PATCH/PUT /parcels/1
  # PATCH/PUT /parcels/1.json
  def update
    respond_to do |format|
      if @parcel.update(parcel_params)
        format.html { redirect_to @parcel, notice: 'Parcel was successfully updated.' }
        format.json { render :show, status: :ok, location: @parcel }
      else
        format.html { render :edit }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parcels/1
  # DELETE /parcels/1.json
  def destroy
    @parcel.destroy
    respond_to do |format|
      format.html { redirect_to parcels_url, notice: 'Parcel was claimed and deleted from database permanently.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parcel
      @parcel = Parcel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parcel_params
      params.require(:parcel).permit(:name, :quantity, :phone, :courier, :remakrs)
    end
    
    def search_params
      params.require(:search).permit(:search_key, :search_type)
    end
    

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_logged_in
  before_action :already_logged_in, except: :destroy

  def new
  end

  def create
    if params[:username] == 'admin'
      admin = User.find_by(name: params[:username])
      log_in(admin)
      redirect_to root_url
    else
      google_api = env['omniauth.auth']
      if google_api.extra.id_info.email.match(/\A\d{10}@gmail.com\z/i)
        user = User.from_omniauth(google_api)
        log_in(user)

        redirect_to root_url
      else
        flash[:danger] = 'Access denied. Please only log in using mmu student email'
        redirect_to root_path
        env['omniauth.auth'] = nil
      end
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  private

  def already_logged_in
    if logged_in? 
      redirect_to root_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :check_logged_in
  
  def home
    if logged_in?
      @user = User.find(session[:user_id])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user?, except: :index
  before_action :check_admin, only: :index

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    phone_num = params[:user][:phone].delete("^0-9")
    @user.update_attributes(phone: phone_num)
    flash.now[:success] = "Phone number updated successfully"
    render 'edit'
  end

  def index
    @users = User.all.paginate(page: params[:page])
  end

  private

  def correct_user?
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title = "") 
    base_title = "ParcelTrack"
    if title.empty?
      base_title
    else
      base_title + " | " + title
    end
  end
  
end

app/helpers/parcels_helper.rb
module ParcelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user #returns current user or nil if there's none
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def current_user?(user)
    current_user == user
  end
  
  def logged_in? #returns true false of login state
    !current_user.nil?
  end
  
  def admin?
    current_user.admin?
  end
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class= "footer">
  <small>
    ParcelTrack by Danny
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-inverse navbar-fixed-top" >
  <div class = "container">
    <%= link_to "parceltrack", root_path, id: "logo" %>
    <nav>
      <ul class = "nav navbar-nav navbar-right">
      <% if current_user %>
        
        <% if current_user.admin? %>
        <li><%= link_to "Add Parcels", new_parcel_path %></li>
        <% end %>
        <li><%= link_to "Search", search_path %></li>
        <li><%= link_to "User profile", edit_user_path(current_user) %></li>
        <li><%= link_to "Sign Out", signout_path, id: "sign_out" %></li>


      <% else %>
        <li><%= link_to "Admin login", login_path %></li>
      <% end %>
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= render "layouts/header" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "container">    </div>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    <%= yield %>

  </body>

  <%= render "layouts/footer" %>
  <%= debug(params) if Rails.env.development? %>
</html>

app/views/parcels/_auto_appear.html.erb
<div class="field col-md-2 nameinput">
  <%= text_field_tag "parcel[0][name]", "", class: "namefield", required: true %>
</div>

<div class="field col-md-2">
  <%= number_field_tag "parcel[0][quantity]","", required: true %>
</div>

<div class="field col-md-2">
  <%= text_field_tag "parcel[0][phone]","", required: true %>
</div>

<div class="field col-md-2">
  <%= text_field_tag "parcel[0][courier]" %>
</div>

<div class="field col-md-4">
  <%= text_field_tag "parcel[0][remarks]" %>
</div> 

app/views/parcels/_form.html.erb
<div class = "row">
<%= render "shared/error_messages" %>
<%= form_tag(parcels_path, method: "post") do |f| %>
  <div class="field col-md-2">
    <%= label_tag "Name" %>
  </div>

  <div class="field col-md-2">
    <%= label_tag "Quantity" %>
  </div>

  <div class="field col-md-2">
    <%= label_tag "Phone" %>
  </div>

  <div class="field col-md-2">
    <%= label_tag "Courier" %>
  </div>

  <div class="field col-md-4">
    <%= label_tag "Remarks" %>
  </div>
  
  <div class ="form--auto_appear">
  <!-- Auto appearing form -->
  <%= render "auto_appear" %>
  </div>
  <div class = "actions">
    <%= submit_tag "Submit" %>
  </div>

<% end %>
  
<script>

  var count = 0;
  var form = document.getElementsByClassName("form--auto_appear")[0];
 
  var types = ["text","number","text","text","text"];

  document.body.addEventListener("keypress", function(event){
    if (event.target.classList.contains("namefield") === true){
        count ++;
        var names = [`parcel[${count}][name]`, `parcel[${count}][quantity]`, `parcel[${count}][phone]`, `parcel[${count}][courier]`, `parcel[${count}][remarks]`]; 
        event.target.classList.remove("namefield");
        container = document.createElement("DIV");
        container.id = "form-" + count;        
        for (var i = 0; i < 5; i++){
          var div = document.createElement("DIV");
          if (i == 4){
            div.classList.add("col-md-4");
          }else{
            div.classList.add("col-md-2"); 
          }
          div.classList.add(`field-${count}`);
          div.classList.add("field")
          var field = document.createElement("input");
          field.setAttribute("name", names[i]);
          field.setAttribute("type", types[i]);
          field.setAttribute("onkeydown", "delete_form(event)");
          if (i == 0){
            field.classList.add("nameinput");
            field.classList.add("namefield");
          }
          
          div.appendChild(field);
          container.appendChild(div);
        }
       form.appendChild(container);
    }
    
  });

  function delete_form(event){

    var key = event.keyCode || event.charCode;
    if (key == 8 || key == 46){
      var div = document.getElementsByClassName(event.target.parentNode.classList[1]);
      for (var i=0; i <5; i++){
        value = div[i].childNodes[0].value;
        if (value != "" || div[i].childNodes[0].classList.contains("namefield")){
          return;
        }
      }
      for (var i=0; i < 5; i++){
        x = div[i].childNodes[0];
        x.parentNode.removeChild(x);
      }
    }
    
  };

</script>

app/views/parcels/_table.html.erb
<table class = "table">
  <thead>
    <tr>
      <th>Received</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Phone</th>
      <th>Courier</th>
      <th>Remarks</th>
      <% if current_user.admin? %>
      <th colspan="3">Actions</th>
      <% end %>
    </tr>
  </thead>

  <tbody>

    <% @parcels.each do |parcel| %>
      <tr>
        <td><%= time_ago_in_words(parcel.created_at) %> ago</td>
        <td><%= parcel.name %></td>
        <td><%= parcel.quantity %></td>
        <td><%= parcel.phone %></td>
        <td><%= parcel.courier %></td>
        <td><%= parcel.remarks %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Edit', edit_parcel_path(parcel) %></td>
        <td><%= link_to 'Claimed', parcel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/parcels/edit.html.erb
<h1>Editing Parcel</h1>

<div id = "parcel_edit" class = "jumbotron row">
<%= form_for @parcel do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :quantity %>
  <%= f.number_field :quantity %>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <%= f.label :courier %>
  <%= f.text_field :courier %>
  <%= f.label :remarks %>
  <%= f.text_field :remarks %>
  <div class = "submit">
  <%= f.submit "Update", class: "btn col-md-4" %>
  </div>
<% end %>
</div>
<%= link_to 'Show', @parcel %> |
<%= link_to 'Back', parcels_path %>

app/views/parcels/index.html.erb
<h1>Parcels</h1>
<div class = "container">
  <h2 class = "text-center">Search Parcel</h2>
  <div>
  <%= form_for(:search, url: search_path) do |f| %>
  <%= f.text_field :search_key, class: "form-control", value: @search_key %>
  <br>
  <%= f.label :Search_by %>
  <%= f.select :search_type, ["name", "phone"], class: "form-control", selected: @search_type %>
  <br><br>
  <%= f.submit "Search", class: "btn" %>
  <% end %>
  
  </div>
</div>
<% if @parcels.nil? %>
<br>
<div class = "jumbotron container-fluid">
  <h3>No related parcel found. Try:</h3>
  <ol>
    <li>Checking your search keyword</li>
    <li>Use another search method</li>
  </ol>
</div>

<% else %>
<%= will_paginate @parcels %>
<%= render "table" %>

<br>
<%= will_paginate %>
<% end %>

app/views/parcels/new.html.erb
<h1>New Parcel</h1>

<%= render 'form', parcel: @parcel %>

<%= link_to 'Back', parcels_path %>

app/views/parcels/new.js.erb
$(".auto_appear").html("<%= escape_javascript(render "auto_appear") %>");
$("#notice").html("<%= j flash[:info] %>")

app/views/parcels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parcel.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @parcel.quantity %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @parcel.phone %>
</p>

<p>
  <strong>Courier:</strong>
  <%= @parcel.courier %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @parcel.remarks %>
</p>

<%= link_to 'Edit', edit_parcel_path(@parcel) %> |
<%= link_to 'Back', parcels_path %>

app/views/shared/_error_messages.html.erb
<% if @error_messages.any? %>
  <div id = "error_messages">
    <div class = "alert alert-danger">
      The form contains <%= pluralize(@error_messages.count, "error") %> errors.
    </div>
    <ul>
      <% @error_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class = "container-fluid row">
  <h1 class = "text-center col-md-12">ParcelTrack</h1>
  <h3 class = "text-center col-md-12">A web application to track your parcel easily</h3>
  <div class = "jumbotron col-md-offset-4 col-md-4" style="padding-top:0px;">
  <h3>How to find your parcel:</h3>
  <ol>
    <li>Log in to verify your identity</li>
    <li>View the list of parcels</li>
    <li>Search for your parcel</li>
  </ol>
  <% unless logged_in? %>
  <%= link_to "Login", "/auth/google_oauth2", class: "btn btn-primary btn-lg", id: "sign_in" %> 
  <% else %>
  <p>You are logged in as <%= @user.name %></p>
  <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <span class = "col-md-2">
  <%= link_to user.name, user %>
  </span>
  <span class = "col-md-2">
  <%= user.phone %>
  </span>
  <span class = "col-md-2">
  <%= user.created_at %>
  </span>
  <span class = "col-md-2">
  <%= time_ago_in_words(user.updated_at) %>
  </span>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>
<h1>Profile settings</h1>
<h1>Welcome, <%= @user.name %>!</h1>
<br><br><br>
<div class = "container">
<div class = "jumbotron col-md-4 col-md-offset-4" >

<%= form_for (@user) do |f| %>
  <%= f.label :Phone %>
  <%= f.text_field :phone, class: "form-control"%>
<!--
  <% if current_user.admin? %>
    <%= f.label :Email %>
    <%= f.text_field :email %>
    <%= f.label :Change_Password %>
    <%= f.password_field :password %>
  <% end %>
  -->
  <br>
  <%= f.submit "Update phone number", class: "btn" %>
<% end %>
</div>
</div>
<br>

app/views/users/index.html.erb
<% provide(:title, "Logged in users") %>
<h1>List of users logged in</h1>
<h3 class = "text-center">The creepy function for administrator :P</h3>
<div class = "row">
  <ul class = "users">
    <%= render @users %>
  </ul>
</div>